In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv("datatset_2010-capitalbikeshare-tripdata_PE42_Tanmay Kapoor_DecisionTreeAlgorithm.csv")
dataset.head(30)

Duration       Start date         End date  Start station number  \
0       1012  9/20/2010 11:27  9/20/2010 11:43                 31208   
1         61  9/20/2010 11:41  9/20/2010 11:42                 31209   
2       2690  9/20/2010 12:05  9/20/2010 12:50                 31600   
3       1406  9/20/2010 12:06  9/20/2010 12:29                 31600   
4       1413  9/20/2010 12:10  9/20/2010 12:34                 31100   
5        982  9/20/2010 12:14  9/20/2010 12:30                 31109   
6        930  9/20/2010 12:15  9/20/2010 12:30                 31109   
7       1659  9/20/2010 12:16  9/20/2010 12:44                 31111   
8       2496  9/20/2010 12:18  9/20/2010 13:00                 31600   
9       1487  9/20/2010 12:19  9/20/2010 12:44                 31703   
10      1007  9/20/2010 12:21  9/20/2010 12:38                 31500   
11      1159  9/20/2010 12:26  9/20/2010 12:45                 31603   
12        88  9/20/2010 12:31  9/20/2010 12:32                 31602   
13       202  9/20/2010 12:33  9/20/2010 12:36                 31105   
14      1407  9/20/2010 12:39  9/20/2010 13:02                 31101   
15       351  9/20/2010 12:39  9/20/2010 12:45                 31103   
16       416  9/20/2010 12:40  9/20/2010 12:47                 31105   
17      2988  9/20/2010 12:41  9/20/2010 13:31                 31206   
18       636  9/20/2010 12:42  9/20/2010 12:52                 31002   
19       509  9/20/2010 13:07  9/20/2010 13:16                 31205   
20       638  9/20/2010 13:13  9/20/2010 13:23                 31201   
21       763  9/20/2010 13:16  9/20/2010 13:29                 31602   
22       387  9/20/2010 13:20  9/20/2010 13:27                 31009   
23      1409  9/20/2010 13:22  9/20/2010 13:46                 31600   
24      1254  9/20/2010 13:27  9/20/2010 13:48                 31002   
25      1238  9/20/2010 13:28  9/20/2010 13:48                 31002   
26       277  9/20/2010 13:30  9/20/2010 13:34                 31106   
27      1532  9/20/2010 13:34  9/20/2010 13:59                 31200   
28       759  9/20/2010 13:40  9/20/2010 13:53                 31104   
29       433  9/20/2010 13:55  9/20/2010 14:02                 31011   

                           Start station  End station number  \
0               M St & New Jersey Ave SE               31108   
1                         1st & N St  SE               31209   
2                          5th & K St NW               31100   
3                          5th & K St NW               31602   
4          19th St & Pennsylvania Ave NW               31201   
5                          7th & T St NW               31200   
6                          7th & T St NW               31105   
7                         10th & U St NW               31208   
8                          5th & K St NW               31601   
9               Minnesota Ave Metro/DOES               31603   
10                         4th & W St NE               31200   
11                         1st & M St NE               31603   
12               Park Rd & Holmead Pl NW               31602   
13                  14th & Harvard St NW               31103   
14                        14th & V St NW               31100   
15                  16th & Harvard St NW               31104   
16                  14th & Harvard St NW               31207   
17                    19th & E Street NW               31603   
18                     20th & Crystal Dr               31003   
19                        21st & I St NW               31200   
20                        15th & P St NW               31200   
21               Park Rd & Holmead Pl NW               31109   
22                     27th & Crystal Dr               31009   
23                         5th & K St NW               31100   
24                     20th & Crystal Dr               31012   
25                     20th & Crystal Dr               31012   
26              Calvert & Biltmore St NW   

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115597 entries, 0 to 115596
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   Duration              115597 non-null  int64 
 1   Start date            115597 non-null  object
 2   End date              115597 non-null  object
 3   Start station number  115597 non-null  int64 
 4   Start station         115597 non-null  object
 5   End station number    115597 non-null  int64 
 6   End station           115597 non-null  object
 7   Bike number           115597 non-null  object
 8   Member type           115597 non-null  object
dtypes: int64(3), object(6)
memory usage: 7.9+ MB


In [4]:
X = dataset.iloc[:,[0,3,5]].values
y = dataset.iloc[:, -1].values
print(X[:5])
print(y[:5])

[[ 1012 31208 31108]
 [   61 31209 31209]
 [ 2690 31600 31100]
 [ 1406 31600 31602]
 [ 1413 31100 31201]]
['Member' 'Member' 'Member' 'Member' 'Member']


In [5]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print("Sample y: ",y[:5])
print("0 : ",labelencoder_y.classes_[0])
print("1 : ",labelencoder_y.classes_[1])

Sample y:  [1 1 1 1 1]
0 :  Casual
1 :  Member


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=0)

In [7]:
classifier = DecisionTreeClassifier(criterion='gini',splitter='random', min_samples_leaf=4, random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_leaf=4, random_state=0, splitter='random')

In [8]:
ypred = classifier.predict(X_test)
ypred

array([1, 1, 1, ..., 1, 1, 1])

In [9]:
cm = confusion_matrix(y_test, ypred)
cm

array([[ 2548,  2326],
       [ 1277, 16969]], dtype=int64)

In [10]:
from sklearn.metrics import accuracy_score
print("Accuracy: ",accuracy_score(y_test,ypred)*100)

Accuracy:  84.41608996539792


In [11]:
from sklearn.metrics import classification_report
print("Report : ",classification_report(y_test,ypred))

Report :                precision    recall  f1-score   support

           0       0.67      0.52      0.59      4874
           1       0.88      0.93      0.90     18246

    accuracy                           0.84     23120
   macro avg       0.77      0.73      0.74     23120
weighted avg       0.83      0.84      0.84     23120

